[package]
name = "rust_snake"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
license = "MIT"
edition = "2018"

[dependencies]
piston = "0.52.1"
piston2d-graphics = "0.37.0"
pistoncore-glutin_window = "0.67.2"
piston2d-opengl_graphics = "0.74.0"
conrod_core = "0.71.0"
conrod_piston = "0.71.0"
piston_window = "0.114.0"
find_folder = "0.3.0"
rusttype = "0.8.1"
gfx_device_gl = "0.16.2"
gfx_core = "0.9.2"
vecmath = "1.0.0"
serde = { version = "1.0.125", features = ["derive"] }
ron= "0.6.4"
rand= "0.8.3"
# force newer version, not needed directly
linked-hash-map = "0.5.4"
