[package]
name = "rust_snake"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
license = "MIT"
edition = "2018"

[dependencies]
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"
conrod_core = "0.63.0"
conrod_piston = "0.63.0"
piston_window = "0.89.0"
find_folder = "0.3.0"
rusttype = "0.8.3"
gfx_device_gl = "0.16.0"
gfx_core = "0.9.0"
vecmath = "0.3.1"
serde = {version = "1.0", features= ["derive"]}
ron="0.5.1"
rand="0.7.2"
