language: rust
rust:
- stable
- beta
- nightly
os:
- osx
- linux
- windows
dist: bionic
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
deploy:
  provider: releases
  token:
    secure: lllzHZ7/BmsZYhWqbBOY8R4eWzNrT3aiXQHDn5DZaHZJzJE4M5fSmsYGkaYFE5khYiQ7lVZNS6lukV7rooi3/TggrbVTVVmStl//Gc4bxJM22WSd4okthmIXm6ZRE+nMDWw7BB853KfxLqs9Rhq+aCgUcmYriornpAhnhcdQjPoSJ2mjfM5WqUvJNWBcI/36vZB066DXDTdrAPJy7+3cwlqs7mu7kR60AsBpW3An9xVWaMebRaYvFWyeOtP5s922vu3V9IXtLFdG2rVtzQ7VPB2BACJZ+U+lXj+9/jVPbvbR7tIYR72HTY6GehJ9/loQhwR9ol0Y96YQ+ys9rcPqHmARv60/BKz+MTYPRd7VlDLrlB3XKPsyRxtYBh4PIHLWNluinr23wH+8B9EmPAZKSHw9dwaOIC4rdcLAN7Ios84XV2ZBEv3ajaK6YY//EMiATk6SMankZ+d8rws7U9K71V0bXq11+GSEYroNudlGdKiOaznw1TTS+qJ9iwfgs05ZvhXr+a38A4AAhyQeGiGOofiQ/raIGJfgp2qWN4jzbQ+r+XmsmN6TU0Jijt7mZSeSWB0p2vk+2mHsF4qtkckkTalOP1kn2P6mXXMX4KaArsoyXq9nkb/Z/U+LHSwnGufQJXjSE5Su5YNo39cnMUIQyHAC8vc9DjD869fSXRsAZPQ=
  file: 
    - 'target/*/rust_snake'
  file_glob: true
  skip_cleanup: true
  cleanup: false
  on:
    repo: Skgland/Snake
    tags: true
